baseURL: "https://www.ryanbuckley.uk"
languageCode: "en-GB"
title: "Ryan Buckley's Website"
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: catppuccin-macchiato
    tabWidth: 4
services:
  googleAnalytics:
    id: "G-V1G54KEXZS"
