baseURL: "https://www.ryanbuckley.uk"
languageCode: "en-GB"
title: "Ryan Buckley"
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: onedark
    tabWidth: 4
