name: CI Build

on: [ pull_request, push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: true
          fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    - name: Install NPM Dependencies
      run: npm i -y

    - name: Build
      run: hugo --minify
